# Generated by Django 5.1.3 on 2025-03-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=models.ImageField(default=1, upload_to='product_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=models.ImageField(default=1, upload_to='product_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=models.ImageField(upload_to='product_image/'),
        ),
    ]
