# Generated by Django 5.1.6 on 2025-03-20 09:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_product_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image1',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image2',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image3',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_image'),
        ),
    ]
